package com.intern.testcases;

import com.github.javafaker.Faker;
import com.intern.base.TestBase2;
import com.intern.pages.*;
import com.intern.util.NavigationBar;
import com.intern.util.ScrollDown;
import com.intern.util.ScrollUp;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.IOException;

public class TestCaseMix extends TestBase2 {

    private CarouselPage carouselpage;
    private NavigationBar navigationbar;
    private LoginPage loginpage;
    private HomePage homepage;
    private FeedPage feedpage;
    private DiscoverPage discoverpage;
    private ScrollDown scrolldown;
    private AddComment addcomment;
    private AddPost addpost;
    private ScrollUp scrollup;
    private OnBoardingPage onboardingpage;
    private Faker faker;
    private AddProduct addproduct;

    public TestCaseMix(){
        super();
    }

    @BeforeMethod
    public void setup() throws IOException, InterruptedException {
        initialization();
        carouselpage = new CarouselPage();
        navigationbar = new NavigationBar();
        loginpage = new LoginPage();
        homepage = new HomePage();
        feedpage = new FeedPage();
        discoverpage = new DiscoverPage();
        scrolldown = new ScrollDown();
        addcomment = new AddComment();
        addpost = new AddPost();
        scrollup = new ScrollUp();
        onboardingpage = new OnBoardingPage();
        faker = new Faker();
        addproduct = new AddProduct();
    }

    @AfterMethod
    public void tearDown(){
        driver.quit();
    }

    @Test
    public void testMix() throws InterruptedException {
        carouselpage.tapNextBtn();
        carouselpage.tapNextBtn();
        carouselpage.tapStartBtn();
        onboardingpage.tapLoginBtn();
        loginpage.loginField(prop.getProperty("user"), prop.getProperty("pass"));
        loginpage.tapSigninBtn();
        Thread.sleep(4000);
        homepage.tapXBtn();
        addproduct.tapPlusBtn();
        addproduct.tapBtnAddReview();
        addproduct.tapProfilBtn();
        Thread.sleep(5000);
        addproduct.tapTakeBtn();
        addproduct.tapHoldBtn();
        addproduct.tapBrandBtn();
        addproduct.tapBrandsBtn();
        addproduct.tapProdukBtn();
        addproduct.tapProdukCategoryBtn();
        addproduct.tapMoisturizerBtn();
        addproduct.ProdukNameBtn("kreatifitas");
        addproduct.ShadeBtn("inovatif");
        addproduct.edtTextDesc(faker.lorem().sentence(35));
        addproduct.SetPriceBtn("1.000.000.000");
        addproduct.SetMoneyBtn();
        addproduct.EuroBtn();
        addproduct.setBtnAddProduct();
        homepage.tapNotifBtn();
        Thread.sleep(2000);
        scrolldown.ScrollDown();
        scrollup.ScrollUp();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrollup.ScrollUp();
        scrollup.ScrollUp();
        scrollup.ScrollUp();
        Thread.sleep(4000);
        homepage.tapFotoBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavFeed();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        feedpage.tapViewBtn();
        feedpage.tapReviewBtn();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        feedpage.tapBackBtn();
        homepage.tapXBtn();
        Thread.sleep(4000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        addcomment.tapBtnComen();
        addcomment.CommentField("awesome");
        addcomment.tapPostBtn();
        feedpage.tapBackBtn();
        navigationbar.tapBtnNavDiscover();
        discoverpage.tapViewBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("amazing");
        addcomment.tapPostBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        Thread.sleep(4000);
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavFeed();
        addpost.tapPlusBtn();
        addpost.tapAddPostBtn();
        addpost.tapOkeBtn();
        addpost.tapAllowBtn();
        addpost.tapTakeBtn();
        addpost.tapAllow2Btn();
        addpost.tapholdBtn();
        addpost.tapCorrectBtn();
        addpost.tapTagBtn();
        addpost.tapCheckBtn();
        addpost.tapDoneBtn();
        addpost.tapCorrect2Btn();
        addpost.tapReviewBtn();
        homepage.tapBtnBack2();
        addpost.editCaption("ini uji coba post yaa");
        addpost.tapHold2Btn();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavFeed();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapLikeBtn();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavProfile();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        Thread.sleep(2000);
        addcomment.tapFotoBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("ini gud");
        addcomment.tapPostBtn();
        Thread.sleep(2000);
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavDiscover();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavDiscover();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavDiscover();
        navigationbar.tapBtnNavProfile();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        Thread.sleep(4000);
        addcomment.tapPictBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("gooood");
        addcomment.tapPostBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavDiscover();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavDiscover();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavDiscover();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavProfile();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        addcomment.tapPictBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("nice pict");
        addcomment.tapPostBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavHome();
        navigationbar.tapBtnNavDiscover();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("amazing");
        addcomment.tapPostBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        Thread.sleep(3000);
        homepage.tapFotoBtn();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        addcomment.tapPictBtn();
        addcomment.tapBtnComen();
        addcomment.CommentField("very nice");
        addcomment.tapPostBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        homepage.tapBackBtn();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavDiscover();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        Thread.sleep(3000);
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        scrolldown.ScrollDown();
        discoverpage.tapViewBtn();
        discoverpage.tapLikeBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavHome();
        homepage.tapNotifBtn();
        homepage.tapBackBtn();
        navigationbar.tapBtnNavFeed();
        navigationbar.tapBtnNavProfile();
        navigationbar.tapBtnNavHome();

    }
}